### ISSUE TITLE
Is not fortran

### ISSUE THREAD

**Issue by stefankiebacher** [benjamin-ca/course_kseta#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by augsteinboson** [comment]
I think this is not only worth an 'enhancement' tag.

**Comment by augsteinboson** [comment]
There should be more.

**Comment by augsteinboson** [comment]
Like 'critical'

**Comment by stefankiebacher** [comment]
I did not do this. @benjamin-ca  forced me to
